production:
  solr:
    hostname: redinnovacion.org
    port: 8080
    path: /solr/ndi-lac
    log_level: WARNING
    auto_commit_after_request: true
    auto_commit_after_delete_request: true
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    path: /solr/ndi-lac
    log_level: INFO
    auto_commit_after_request: true
    auto_commit_after_delete_request: true

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
